<?php

/**
 * Content for the 12 dedicated "Solutions" pages (nav → Solutions dropdown).
 * One place to edit copy for all of them — each page's Blade file and
 * PublicController method just pull their row out of this array by slug.
 *
 * 'image' is a real photo (public/assets/images/industries/*.jpg) for the
 * original 6 solutions. The 6 newer categories have no photography yet, so
 * 'image' is null and 'icon_svg' (raw <path>/<rect> markup, 24x24 viewBox)
 * is used instead — never substitute a mismatched stock photo for a real one.
 */

return [

    'limo-services' => [
        'name'               => 'Limo Services',
        'title'              => 'Limo Booking Software | LimoSchedule',
        'meta_description'   => 'White-label limo booking software with an automated booking website, admin dashboard and fare calculator — replace phone bookings with online reservations.',
        'eyebrow'            => 'Solution for Limo Services',
        'heading'            => 'Turn Phone-Based Limo Bookings Into an Automated Website',
        'challenge'          => 'Manual phone bookings and paper schedules make it hard to look professional or scale.',
        'helps'              => 'A branded booking website and admin dashboard replace phone tag with automated online reservations and centralized dispatch.',
        'bullets'            => ['Advanced Booking', 'Fare Calculator', 'White-Label Branding', 'Admin Dashboard'],
        'cta_label'          => 'Get Started With Limo Booking Software',
        'image'              => 'public/assets/images/industries/limo-services.jpg',
        'image_alt'          => 'Limo service booking software showing an automated online reservation platform',
        'icon_svg'           => null,
        'service_name'       => 'Limo Booking Software',
        'service_description'=> 'White-label booking website and admin dashboard for limo services, replacing phone-based bookings with automated online reservations and centralized dispatch.',
    ],

    'black-car-services' => [
        'name'               => 'Black Car Services',
        'title'              => 'Black Car Booking Software | LimoSchedule',
        'meta_description'   => 'White-label black car booking software with a branded website and customer panel — give premium clients a polished, self-service reservation experience.',
        'eyebrow'            => 'Solution for Black Car Services',
        'heading'            => 'Give Premium Clients a Booking Experience That Matches Your Service',
        'challenge'          => 'Corporate and premium clients expect a polished, self-service reservation process — not a phone call.',
        'helps'              => 'A white-label booking website and customer panel let clients book, view and manage rides themselves, entirely under your own brand.',
        'bullets'            => ['White-Label Branding', 'Customer Panel', 'Mobile Responsive', 'Advanced Booking'],
        'cta_label'          => 'Get Started With Black Car Booking Software',
        'image'              => 'public/assets/images/industries/black-car-services.jpg',
        'image_alt'          => 'Black car service booking website with a premium self-service customer panel',
        'icon_svg'           => null,
        'service_name'       => 'Black Car Booking Software',
        'service_description'=> 'White-label booking website and customer panel for black car services, giving premium clients a self-service reservation experience under their own brand.',
    ],

    'taxi-companies' => [
        'name'               => 'Taxi Companies',
        'title'              => 'Taxi Dispatch & Booking Software | LimoSchedule',
        'meta_description'   => 'Taxi booking software connecting bookings, dispatch and drivers in one system — admin dashboard, driver panel and fare calculator included.',
        'eyebrow'            => 'Solution for Taxi Companies',
        'heading'            => 'Connect Bookings, Dispatch and Drivers in One System',
        'challenge'          => 'Juggling bookings, driver assignments and daily operations across separate tools slows dispatch down.',
        'helps'              => 'The admin dashboard and driver panel connect every booking straight to the right driver, with no manual re-entry.',
        'bullets'            => ['Driver Panel', 'Admin Dashboard', 'Advanced Booking', 'Fare Calculator'],
        'cta_label'          => 'Get Started With Taxi Booking Software',
        'image'              => 'public/assets/images/industries/taxi-companies.jpg',
        'image_alt'          => 'Taxi company dispatch software connecting bookings to drivers',
        'icon_svg'           => null,
        'service_name'       => 'Taxi Booking Software',
        'service_description'=> 'Admin dashboard and driver panel for taxi companies, connecting bookings, dispatch and drivers in one system.',
    ],

    'chauffeur-services' => [
        'name'               => 'Chauffeur Services',
        'title'              => 'Chauffeur Booking Software | LimoSchedule',
        'meta_description'   => 'Chauffeur service booking software with connected customer, driver and admin panels — track every trip from booking to drop-off.',
        'eyebrow'            => 'Solution for Chauffeur Services',
        'heading'            => 'Keep Every Trip Tracked From Booking to Drop-Off',
        'challenge'          => 'Coordinating customers, drivers and bookings by hand leads to missed details and inconsistent service.',
        'helps'              => 'Customer, driver and admin panels stay connected, so every trip is tracked automatically from booking to completion.',
        'bullets'            => ['Customer Panel', 'Driver Panel', 'Admin Dashboard', 'White-Label Branding'],
        'cta_label'          => 'Get Started With Chauffeur Booking Software',
        'image'              => 'public/assets/images/industries/chauffeur-services.jpg',
        'image_alt'          => 'Chauffeur service booking software tracking a trip from booking to drop-off',
        'icon_svg'           => null,
        'service_name'       => 'Chauffeur Booking Software',
        'service_description'=> 'Connected customer, driver and admin panels for chauffeur services, tracking every trip from booking to drop-off.',
    ],

    'airport-transfers' => [
        'name'               => 'Airport Transfer Services',
        'title'              => 'Airport Transfer Booking Software | LimoSchedule',
        'meta_description'   => 'Airport transfer booking software with advanced booking and a connected driver panel — keep every pickup on schedule and visible to your team.',
        'eyebrow'            => 'Solution for Airport Transfer Services',
        'heading'            => 'Keep Every Pickup On Schedule, Every Time',
        'challenge'          => 'Late pickups and scheduling mix-ups cost airport transfer businesses repeat customers.',
        'helps'              => 'Advanced booking and a connected driver panel keep pickup times accurate and visible to your whole team.',
        'bullets'            => ['Advanced Booking', 'Driver Panel', 'Fare Calculator', 'Mobile Responsive'],
        'cta_label'          => 'Get Started With Airport Transfer Booking Software',
        'image'              => 'public/assets/images/industries/airport-transfer.jpg',
        'image_alt'          => 'Airport transfer booking software showing an accurately scheduled pickup',
        'icon_svg'           => null,
        'service_name'       => 'Airport Transfer Booking Software',
        'service_description'=> 'Advanced booking and a connected driver panel for airport transfer businesses, keeping pickup times accurate and visible to the whole team.',
    ],

    'corporate-travel' => [
        'name'               => 'Corporate Travel',
        'title'              => 'Corporate Travel Booking Software | LimoSchedule',
        'meta_description'   => 'Corporate travel booking software with multi-currency, multi-language support and white-label branding — professional booking for business accounts.',
        'eyebrow'            => 'Solution for Corporate Travel',
        'heading'            => 'Give Business Accounts a Professional Booking Experience',
        'challenge'          => 'Corporate clients expect a professional, always-available booking process with transparent pricing.',
        'helps'              => 'A branded, mobile-responsive booking website with multi-currency support keeps corporate accounts running smoothly worldwide.',
        'bullets'            => ['Multi-Currency', 'Multi-Language', 'White-Label Branding', 'Admin Dashboard'],
        'cta_label'          => 'Get Started With Corporate Travel Booking Software',
        'image'              => 'public/assets/images/industries/corporate-travel.jpg',
        'image_alt'          => 'Corporate travel booking platform for managing business travel accounts',
        'icon_svg'           => null,
        'service_name'       => 'Corporate Travel Booking Software',
        'service_description'=> 'Branded, mobile-responsive booking website with multi-currency support for corporate travel accounts.',
    ],

    'wedding-transportation' => [
        'name'               => 'Wedding Transportation',
        'title'              => 'Wedding Transportation Booking Software | LimoSchedule',
        'meta_description'   => 'Wedding transportation booking software with advanced booking and driver coordination — keep every pickup on schedule for the big day, under your own brand.',
        'eyebrow'            => 'Solution for Wedding Transportation',
        'heading'            => 'Keep Every Wedding-Day Pickup Right on Schedule',
        'challenge'          => 'Wedding transportation needs flawless timing and a polished, professional booking experience for such a big day.',
        'helps'              => 'Advanced booking and driver coordination keep every pickup on schedule, while white-label branding keeps the experience fully yours.',
        'bullets'            => ['Advanced Booking', 'White-Label Branding', 'Driver Panel', 'Mobile Responsive'],
        'cta_label'          => 'Get Started With Wedding Transportation Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<path d="M20.8 4.6c-1.7-1.6-4.4-1.6-6.1 0L12 7.1 9.3 4.6c-1.7-1.6-4.4-1.6-6.1 0-1.8 1.7-1.8 4.4 0 6.1L12 19l8.8-8.3c1.8-1.7 1.8-4.4 0-6.1z"/>',
        'service_name'       => 'Wedding Transportation Booking Software',
        'service_description'=> 'Advanced booking and driver coordination for wedding transportation, with white-label branding to keep the experience under your own brand.',
    ],

    'event-transportation' => [
        'name'               => 'Event Transportation',
        'title'              => 'Event Transportation Booking Software | LimoSchedule',
        'meta_description'   => 'Event transportation booking software for coordinating multiple vehicles and pickup points from one admin dashboard and driver panel.',
        'eyebrow'            => 'Solution for Event Transportation',
        'heading'            => 'Coordinate Multi-Vehicle Event Transportation From One Dashboard',
        'challenge'          => 'Group events and large parties need reliable scheduling across multiple vehicles and pickup points.',
        'helps'              => 'The admin dashboard and driver panel coordinate multiple vehicles and routes from one place, keeping every guest on time.',
        'bullets'            => ['Admin Dashboard', 'Driver Panel', 'Advanced Booking', 'Fare Calculator'],
        'cta_label'          => 'Get Started With Event Transportation Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>',
        'service_name'       => 'Event Transportation Booking Software',
        'service_description'=> 'Admin dashboard and driver panel for event transportation, coordinating multiple vehicles and pickup points from one place.',
    ],

    'hotel-resort-transfers' => [
        'name'               => 'Hotel & Resort Transfers',
        'title'              => 'Hotel & Resort Transfer Booking Software | LimoSchedule',
        'meta_description'   => 'Hotel and resort transfer booking software with a branded website and customer panel — let guests book instant transfers without phone calls.',
        'eyebrow'            => 'Solution for Hotel & Resort Transfers',
        'heading'            => 'Let Guests Book Transfers Instantly — No Phone Calls Needed',
        'challenge'          => 'Hotel and resort guests expect instant, professional transfer booking without phone calls or delays.',
        'helps'              => 'A branded booking website lets guests reserve transfers instantly, while the customer panel keeps them updated in real time.',
        'bullets'            => ['Customer Panel', 'White-Label Branding', 'Mobile Responsive', 'Advanced Booking'],
        'cta_label'          => 'Get Started With Hotel & Resort Transfer Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<rect x="4" y="2" width="16" height="20" rx="1"/><line x1="9" y1="7" x2="9" y2="7"/><line x1="15" y1="7" x2="15" y2="7"/><line x1="9" y1="12" x2="9" y2="12"/><line x1="15" y1="12" x2="15" y2="12"/><line x1="9" y1="17" x2="15" y2="17"/>',
        'service_name'       => 'Hotel & Resort Transfer Booking Software',
        'service_description'=> 'Branded booking website and customer panel for hotel and resort transfers, letting guests reserve transfers instantly without phone calls.',
    ],

    'tour-travel-transportation' => [
        'name'               => 'Tour & Travel Transportation',
        'title'              => 'Tour & Travel Booking Software | LimoSchedule',
        'meta_description'   => 'Tour and travel transportation booking software with multi-stop advanced booking, multi-currency and multi-language support for international travelers.',
        'eyebrow'            => 'Solution for Tour & Travel Transportation',
        'heading'            => 'Manage Multi-Stop Tours and Group Bookings With Ease',
        'challenge'          => 'Tour operators need to manage multi-stop itineraries and group bookings without losing track of details.',
        'helps'              => 'Advanced booking and multi-currency support make it easy to handle group tours and international travelers alike.',
        'bullets'            => ['Advanced Booking', 'Multi-Currency', 'Multi-Language', 'Admin Dashboard'],
        'cta_label'          => 'Get Started With Tour & Travel Booking Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"/><line x1="8" y1="2" x2="8" y2="18"/><line x1="16" y1="6" x2="16" y2="22"/>',
        'service_name'       => 'Tour & Travel Booking Software',
        'service_description'=> 'Advanced booking with multi-currency and multi-language support for tour and travel transportation businesses managing group itineraries.',
    ],

    'party-bus-services' => [
        'name'               => 'Party Bus Services',
        'title'              => 'Party Bus Booking Software | LimoSchedule',
        'meta_description'   => 'Party bus booking software with an automatic fare calculator and admin dashboard — manage group bookings and pricing without the manual work.',
        'eyebrow'            => 'Solution for Party Bus Services',
        'heading'            => 'Automate Group Pricing and Bookings for Every Party Bus Run',
        'challenge'          => 'Party bus bookings involve large groups, specific timing and premium pricing that\'s hard to manage manually.',
        'helps'              => 'The fare calculator and admin dashboard handle group pricing and bookings automatically, so nothing slips through the cracks.',
        'bullets'            => ['Fare Calculator', 'Admin Dashboard', 'Advanced Booking', 'Mobile Responsive'],
        'cta_label'          => 'Get Started With Party Bus Booking Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
        'service_name'       => 'Party Bus Booking Software',
        'service_description'=> 'Fare calculator and admin dashboard for party bus services, automating group pricing and bookings.',
    ],

    'executive-transportation' => [
        'name'               => 'Executive Transportation',
        'title'              => 'Executive Transportation Booking Software | LimoSchedule',
        'meta_description'   => 'Executive transportation booking software with white-label branding and a customer panel — deliver the discreet, professional experience executives expect.',
        'eyebrow'            => 'Solution for Executive Transportation',
        'heading'            => 'Give Executive Clients a Discreet, Professional Booking Experience',
        'challenge'          => 'Executive and corporate clients expect a discreet, reliable and professional booking experience every time.',
        'helps'              => 'White-label branding and a customer panel deliver the polished, self-service experience executive clients expect.',
        'bullets'            => ['White-Label Branding', 'Customer Panel', 'Driver Panel', 'Admin Dashboard'],
        'cta_label'          => 'Get Started With Executive Transportation Software',
        'image'              => null,
        'image_alt'          => null,
        'icon_svg'           => '<rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16"/>',
        'service_name'       => 'Executive Transportation Booking Software',
        'service_description'=> 'White-label branding and a customer panel for executive transportation, delivering a discreet, professional self-service booking experience.',
    ],

];
